chore: added ksync to kyve docs
KYVENetwork/docs pull request #111
Opened 2024-04-24 07:12 UTC by troykessler

2024-05-02 13:17 UTC, mbreithecker requested changes

2024-05-02 13:17 UTC, mbreithecker commented on docs/validators/chain_nodes/join_network.md
> +wget https://raw.githubusercontent.com/KYVENetwork/networks/main/kyve-1/genesis.json
why do you change the url from our CDN to github?

2024-05-02 13:17 UTC, mbreithecker commented on docs/validators/chain_nodes/join_network.md
> +Since KYVE has validated and archived all of it's own state-sync snapshots on a 3,000 block interval those can be used
"its"

2024-05-02 13:17 UTC, mbreithecker commented on docs/validators/chain_nodes/join_network.md
> +to bootstrap you KYVE node. For this the node-syncing tool [KSYNC](/docs/validators/ksync/index.md) can be used. To install
"your"

2024-05-02 13:17 UTC, mbreithecker commented on docs/validators/chain_nodes/join_network.md
> +Since KYVE has validated and archived all of it's own blocks and block results they can be used to sync the node instead of fetching them from the P2P network.
"its"

2024-05-02 13:27 UTC, troykessler commented on docs/validators/chain_nodes/join_network.md
> +wget https://raw.githubusercontent.com/KYVENetwork/networks/main/kyve-1/genesis.json
Because I thought github is the source of truth and then it matches the entry in the cosmos chain registry

2024-05-13 11:41 UTC, mbreithecker approved these changes

2024-05-13 11:41 UTC, merged